### ISSUE TITLE
Proposal: namespace mixins and variables

### ISSUE THREAD

**Issue by darbymanning** [neuekit/neuekit#68]
It would be useful if variables and mixins were namespaced similar to how we have namespaced the actual components. For example `$rootFontSize` could become `$neue-rootFontSize` or similar.

A couple of reasons:
- Generally considered a good practice, keeps things consistent and tidy
- One main use case for this is when trying to manually include specific parts of neuekit on an existing project (ie. the just the Elements layer for example) there are many (undocumented 😏) dependencies on functions and mixins. Having a namespace would means a potential non-existing `$neue-rootFontSize` has more context as you can see its origin.

If there is a concern on legacy support as this would be a breaking change, then we could just add these as additional variables? But personally I'd rather just let the change mean a little refactor as it's essentially just a find/replace and we have yet to give a public release.

**Comment by darbymanning** [comment]
💬Discussion: connected to this I would also ask the question what naming convention we should use for variables and mixins. Whilst we have imposed a camelCase formatting style for our CSS classes I wonder if we should use spine-case for variables and mixins.

**Comment by darbymanning** [comment]
💬 Discussion: connected to this I would also ask the question what naming convention we should use for variables and mixins. Whilst we have imposed a camelCase formatting style for our CSS classes I wonder if we should use spine-case for variables and mixins.

**Comment by matt3224** [comment]
We can do `$nu_rootFontSize` as i went with `nu` for mixin prefixes.

Thinking about it, spine-case is not commonly used in variable names, even in JS or PHP, should this inform our decision?

Currently we do `nu-element__shared()` for mixins which does use a hyphen mirroring the bemitcss class structure. This felt right at the time as it feels cohesive, plus `nu_element__shared()` detracts from the impact of the double underscore.

Utilising the same rules as the bemitscss class name structure gives us a template to work with for all names:
* We can namespace
* We can assign a parent or local namespace
* We can assign child variables
* We can create predefined overrides using the modifier pattern

Perhaps we simply continue down this path as it has worked so far but with the addition of the namespace as you mention?

**Comment by darbymanning** [comment]
> Thinking about it, spine-case is not commonly used in variable names, even in JS or PHP, should this inform our decision?
Not sure this is true of SCSS variables though? I actually struggle to find any project that doesn't use spinal-case for that. Ditto for functions.

That said I'm fine with the idea of following BEM here. Btw what are your thoughts on namespacing functions? I wouldn't suggest we namespace them as they will make the code look pretty messy (ie. imagine it on all the rem() functions, chain, etc.)

**Comment by matt3224** [comment]
Good point on the function names although i think we may be ok as these would only gain the namespace? `nu-rem()` perhaps that’s acceptible?

**Comment by darbymanning** [comment]
True, it is very concise - so perhaps not a huge issue.

I guess my hesitation is around more common functions that aren't particularly unique to the framework. For example things like `str-replace`, `str-capitalise`. It'd be nice if we could retain their names as-is really rather than them becoming `nu-str-replace` and `nu-str-capitalise`. In fact this is another example of spine-case working nicely. Using BEM-style here would result in `nu-strReplace`. I just think it's a bit naff. What do you think?

**Comment by matt3224** [comment]
The problem with spine case here is that `nu` `str` and `capitalise` are all equal where as BEM gives you the separation of `nu` the namespace and `strReplace` the 2 word function name.

If we want to avoid losing somewhat standard helpers then we should perhaps look at pulling these out completely into a separate repo and treated as a micro library that neuekit uses or and this may be better or infact terrible, i can't decide. We could make a master function that takes the method as the first argument. For example `nu('replace')` a little like how an event listener states the event type.
