### ISSUE TITLE
Proposal: use stateful namespace classes (is- has-)

### ISSUE THREAD

**Issue by darbymanning** [neuekit/neuekit#69]
I'd suggest we do away with `.active` or `--active` in favour of `.is-active`.

https://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces#the-namespaces

I understand the perspective that by the class being present that it clearly is active in this context, but it's further reaching than this -- I'm often using classes such as `.is-loading`, `.has-children` or `.has-dropdown`.

I might need to give some better examples of how this is used. One that isn't my own would be the Choices.js plugin (if you're not familiar with it, it's basically a vanilla JS version of select2). Take a look at the class names they are using by default:

https://github.com/jshjohnson/Choices#classnames

Whilst you could make an argument that `is-` could be removed and those state classes would still make sense, the `has-` state class gives additional meaning. And I would say that having `.is-` & `.has-` means we are consistent in namespacing as we do with components, objects & utilities. This then makes it easier to do health-checks/debugging (ie. something like `[class^=".is-"] { outline: 2px solid red }` would be made possible) - and it provides meaningful context for the class.

**Comment by matt3224** [comment]
I’m in agreement on this one now, Chris and I moved to this awhile ago, framework hasnt caught up yet
