### ISSUE TITLE
Unable to set no max-width on grid

### ISSUE THREAD

**Issue by darbymanning** [neuekit/neuekit#91]
Setting `$nu-gridMaxWidth` to `none` throws an error as it expects an integer.

**Comment by matt3224** [comment]
What made you think you could use `none`?

It's used like this in grid.scss `max-width: nu-rem( $maxWidth );`

We could probably add a condition perhaps to use none if `nu-rem` fails

**Comment by matt3224** [comment]
Fixed in https://github.com/neuekit/neuekit/commit/e052b7995f796bc14dd44cff4453f108d2a3ba73
